project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    html-math-method: katex
  docx: default
  jats: default

  # (other formats)
  typst:
    toc: true

execute:
  freeze: auto
  enabled: true
  cache: true


